---
title: "Assignments"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- ## Introductory assignment (due 5:00 pm Tuesday, August 28, 2018) -->

<!-- This assignment takes the place of "participation" credit for Weeks 1 and 2. It is worth four points, two each for each of the two questions. I prefer that you submit your response as an email or as a text file with "PSY 511 Assignment 1" in the subject line. If you submit a MS Word (.docx) document, please include your name in the file name, e.g. if I were submitting an answer, I would use `psy-511-assignment-1-gilmore.docx`. -->

<!-- I plan to post your answers to the first question on the course website so that we can discuss similarities and differences among our choices. So, please write your answers with that in mind. -->

<!-- ### 1. Pick two papers you want to read and (better) understand (2 points) -->

<!-- - Provide APA formatted citation (with DOIs) -->
<!-- - Indicate three concepts/terms from these papers that you are especially interested in understanding -->

<!-- ### 2. Choose a behavior or mental state you want to (better) understand (2 points) -->

<!-- - Take an information processing perspective and briefly sketch out (in no more than a short paragraph) the main inputs, outputs, and computations involved. -->
<!--   - When thinking about *outputs* make sure to distinguish between *behaviors* (e.g., movements, facial expressions, vocalizations) and *physiological states* (e.g., changes in heart rate, hormone concentrations in the blood, etc.) -->

## Resource write-up

Please write-up a review of i) one of the references you discuss in your symposium presentation or ii) another paper of your choosing in the style of a *Neuron* "Preview" or a *Nature* "Research Highlights" paper ([example](https://www.nature.com/search?article_type=research-highlights&order=date_desc)).

Your review should be 2,000-2,500 words (6-10 pp in length, double-spaced) and is due by **noon on Wednesday, December 18, 2019**.

Here are some examples to get your creative juices flowing:

Bray, N. (2019). Foreseeing compulsion. *Nature Reviews Neuroscience*. Retrieved from http://dx.doi.org/10.1038/s41583-019-0256-8. [PDF](pdf/s41583-019-0256-8.pdf)

Lewis, S. (2019). A good stretch regulates satiety. *Nature Reviews Neuroscience*. Retrieved from http://dx.doi.org/10.1038/s41583-019-0252-z. [PDF](pdf/s41583-019-0252-z.pdf)

Gupta, P. K., & Murphy, T. H. (2019). Cortex-wide computations in complex decision making in mice. *Neuron*, *104*(4), 631–633. Retrieved from http://dx.doi.org/10.1016/j.neuron.2019.10.043. [PDF](pdf/PIIS0896627319309638.pdf)

Mazade, R., & Alonso, J. M. (2019). Synergy in cortical networks. *Neuron*, *104*(2), 184–185. Retrieved from http://dx.doi.org/10.1016/j.neuron.2019.09.041. [PDF](pdf/PIIS089662731930844X.pdf)

## Planning for the student symposium

You have two class periods (~150 mins), how do you want to spend them?

Constraints:

- Everyone must be a lead author on at least one presentation.
- No person should be an author on more than two presentations.
- If every ($n=15$) person presents (as an individual or part of a group), there are less than 10 mins/presentation because of the need for transition times.
- Presentations should try to focus on answering these questions:
  - What do we know about $X$, where $X$ could be the biological basis of some behavior, the behavioral effects of some neurotransmitter, hormone, or drug, the role of some circuit or brain region, or some other topic related to the biological/neurological foundations of human behavior.
  - What _don't_ we know about $X$?
  - Why is it important to answer these questions?
- Some diversity of topics would be good.

Suggested starting point:

- Review the [student interests](interests.html) page. Look for overlapping themes or common interests.
- Is there a group that could do a mini-symposium around some topic? Or would a co-authored single talk make sense?
- Does someone feel strongly about working with a partner/group versus working alone. Either is totally ok.

Final points:

- It's ok to build upon or enhance work you want to do for your research. For example, if you need to review the literature on the role of oxytocin in modulating social behavior for a paper you're writing, it's fine to make that a part of your presentation. You'll just need to make clear to me what new work you're doing for this assignment.

<!-- ## Group presentations -->

<!-- - Provide 2-3 background readings in advance (by Friday, November 30) -->
<!-- - 25 min (max) presentation + 10 min discussion -->
<!-- - Focused themes + integrative section -->
<!--     - What have we learned/what do we know? -->
<!--     - What don't we know? -->
<!--     - Why are these answers important to know? -->
<!--     - How does topic X relate to/inform another theme? -->
<!-- - Submit slides (after talk is fine) -->
<!--     - Statement about who did what -->

<!-- | Group Theme | Members | Presentation Day? | -->
<!-- |-------------|---------|-------------------| -->
<!-- | Measuring brain & behavior | Kelley, Anna, Alison, Lauren, Rhea | | -->
<!-- | Neurodegeneration & disorder | Kaitlin, Sam, Daryl, Emily | | -->
<!-- | Development, aging, & plasticity | Liz, Michael, Lia, Chloe, Nate | | -->
<!-- | Cognition & emotion | Austen, Brandon, Shane, Natalia | | -->

